Slightly customised version of Qt5, using our own SQLite formula
Also note that one of the `inreplace` clauses has been commented
out, as it was causing a compile failure (even in untouched Qt5 formula).

The error it was causing (prior to commenting out) was:

    Error: An exception occurred within a child process:
      Utils::Inreplace::Error: inreplace failed
    `paths` (first) parameter:
      `paths` was empty